version: "3.7"

services:
  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - web
    volumes:
      - ../../../:/workspace
      # Docker socket to access Docker server
      - /var/run/docker.sock:/var/run/docker.sock
      # SSH directory
      - ~/.ssh:/home/vscode/.ssh
      - ~/.ssh:/root/.ssh
      # Git config
      - ~/.gitconfig:/home/districter/.gitconfig
      - ~/.gitconfig:/root/.gitconfig
      # Kubernetes
      # - ~/.kube:/home/districter/.kube
      # - ~/.kube:/root/.kube
      # Samples downloaded from s3.
      - samples:/samples
    environment:
      - TZ=
    cap_add:
      # For debugging with dlv
      - SYS_PTRACE
    security_opt:
      # For debugging with dlv
      - seccomp:unconfined
    entrypoint: zsh -c "while sleep 1000; do :; done"

  couchbase:
    image: couchbase/server:6.6.1
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "11210:11210"
    volumes:
      - couchbase_data:/opt/couchbase/var

  minio:
    image: minio/minio:RELEASE.2021-03-17T02-33-02Z
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data

  nsqlookupd:
    image: nsqio/nsq:v1.2.0
    command: >
      /nsqlookupd
      --log-level error
    hostname: nsqlookupd
    ports:
      - 4160:4160
      - 4161:4161

  nsqd01:
    image: nsqio/nsq:v1.2.0
    command: >
      /nsqd
      --lookupd-tcp-address=nsqlookupd:4160
      --log-level error
    hostname: nsqd01
    depends_on:
      - nsqlookupd
    ports:
      - 4150:4150
      - 4151:4151

  nsqd02:
    image: nsqio/nsq:v1.2.0
    command: >
      /nsqd
      --lookupd-tcp-address=nsqlookupd:4160
      --tcp-address=0.0.0.0:4140
      --http-address=0.0.0.0:4141
      --log-level error
    hostname: nsqd02
    depends_on:
      - nsqlookupd
    ports:
      - 4140:4140
      - 4141:4141

  nsqadmin:
    image: nsqio/nsq:v1.2.0
    command: >
      /nsqadmin
      --lookupd-http-address=nsqlookupd:4161
      --log-level error
    hostname: nsqadmin
    depends_on:
      - nsqlookupd
    ports:
      - 4171:4171

  ml-pipeline:
    image: saferwall/ml-pipeline:latest
    ports:
      - "8001:8001"
    command: "gunicorn -b 0.0.0.0:8001 --chdir api/ app:app"

  web:
    image: saferwall/backend:latest
    ports:
      - "8080:8080"
    environment:
      ENVIRONMENT: dev
    depends_on:
      - minio
      - nsqd01
      - nsqd02
      - couchbase
      - nsqlookupd
    restart: on-failure

  ui:
    image: saferwall/ui:latest
    ports:
      - "8000:80"
    environment:
      VUE_APP_BACKEND_HOST: http://localhost:8080/
    depends_on:
      - web

  avira:
    image: saferwall/goavira:latest
    ports:
      - "50051:50051"
    volumes:
      - samples:/samples

  clamav:
    image: saferwall/goclamav:latest
    ports:
      - "50052:50051"
    volumes:
      - samples:/samples

  comodo:
    image: saferwall/gocomodo:latest
    ports:
      - "50053:50051"
    volumes:
      - samples:/samples

  windefender:
    image: saferwall/gowindefender:latest
    ports:
      - "50054:50051"
    volumes:
      - samples:/samples

volumes:
  minio_data:
  couchbase_data:
  samples:
