apiVersion: v2
name: saferwall
description: A hackable malware sandbox for the 21st Century
type: application
version: 0.4.0
appVersion: 0.4.0
home: https://saferwall.com
icon: https://saferwall.com/favicon.png
sources:
    - https://github.com/saferwall/saferwall
maintainers:
    - name: saferwall
      email: contact@saferwall.com
dependencies:
    - name: minio
      repository: https://charts.min.io/
      version: 5.0.1
      condition: minio.enabled
    - name: couchbase-operator
      version: 2.32.2
      repository: https://couchbase-partners.github.io/helm-charts/
      condition: couchbase-operator.enabled
    - name: aws-efs-csi-driver
      version: 2.2.6
      repository: https://kubernetes-sigs.github.io/aws-efs-csi-driver/
      condition: aws-efs-csi-driver.enabled
    - name: nfs-server-provisioner
      version: 1.8.0
      repository: https://kubernetes-sigs.github.io/nfs-ganesha-server-and-external-provisioner/
      condition: nfs-server-provisioner.enabled
    - name: ingress-nginx
      version: 4.4.2
      repository: https://kubernetes.github.io/ingress-nginx/
      condition: ingress-nginx.enabled
    - name: nsq
      version: 0.0.8
      repository: https://nsqio.github.io/helm-chart/
      condition: nsq.enabled
