{{- if .Values.ml.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template  "saferwall.fullname" . }}-ml
  labels:
    app.kubernetes.io/name: {{ template "saferwall.name" . }}-ml
{{ include "saferwall.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ template "saferwall.name" . }}-ml
  replicas:  {{ .Values.ml.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "saferwall.name" . }}-ml
{{ include "saferwall.labels" . | indent 8 }}
    spec:
      {{ if eq .Values.global.privateRegistryServer true }}
      imagePullSecrets:
        - name: regcred
      {{- end }}
      containers:
        - name: "{{ .Values.ml.name }}"
          image: "{{ .Values.ml.image.repository }}:{{ .Values.ml.image.tag }}"
          ports:
            - containerPort: {{ .Values.ml.containerPort }}
          resources:
            requests:
              memory: "{{ .Values.ml.resources.requests.memory }}"
              cpu: "{{ .Values.ml.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.ml.resources.limits.memory }}"
              cpu: "{{ .Values.ml.resources.limits.cpu }}"
{{- end }}
