{{- if .Values.ui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template  "saferwall.fullname" . }}-ui
  labels:
    app.kubernetes.io/name: {{ template "saferwall.name" . }}-ui
{{ include "saferwall.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ template "saferwall.name" . }}-ui
  replicas:  {{ .Values.ui.replicas }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "saferwall.name" . }}-ui
{{ include "saferwall.labels" . | indent 8 }}
    spec:
      {{ if eq .Values.saferwall.privateRegistryServer.enabled true }}
      imagePullSecrets:
        - name: regcred
      {{- end }}
      containers:
        - name: "{{ .Values.ui.name }}"
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          ports:
            - containerPort: {{ .Values.ui.containerPort }}
          resources:
{{- toYaml .Values.ui.resources | nindent 12 }}
          env:
{{- toYaml .Values.ui.env | nindent 12 }}
{{- end }}
