version: "3.9"

# Use this docker-compose file to setup the test environment before running the
# tests.

services:
  couchbase:
    image: couchbase/server:6.6.2
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "11210:11210"
    volumes:
      - couchbase_data:/opt/couchbase/var

  nsqlookupd:
    image: nsqio/nsq:v1.2.1
    command: >
      /nsqlookupd --log-level=error
    hostname: nsqlookupd
    ports:
      - 4160:4160
      - 4161:4161

  nsqd:
    image: nsqio/nsq:v1.2.1
    command: >
      /nsqd --lookupd-tcp-address=nsqlookupd:4160 --max-msg-size=1413820683
      --log-level=error
    hostname: nsqd
    depends_on:
      - nsqlookupd
    ports:
      - 4150:4150
      - 4151:4151

  nsqadmin:
    image: nsqio/nsq:v1.2.1
    command: >
      /nsqadmin --lookupd-http-address=nsqlookupd:4161 --log-level=error
    hostname: nsqadmin
    depends_on:
      - nsqlookupd
    ports:
      - 4171:4171

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"

  webapis:
    image: saferwall/webapis:latest
    ports:
      - "8080:8080"
    environment:
      - SFW_WEBAPIS_DEPLOYMENT_KIND=dev
    entrypoint:
      [
        /saferwall/server,
        -config,
        /saferwall/conf/,
        -db,
        /saferwall/db,
        -tpl,
        /saferwall/templates
      ]
    restart: always

  ui:
    image: saferwall/ui:latest
    ports:
      - "8000:80"
    environment:
      VUE_APP_BACKEND_HOST: http://localhost:8080/
    depends_on:
      - webapis

  ml:
    image: saferwall/ml-pipeline:latest
    ports:
      - "8000:8000"

  orchestrator:
    image: saferwall/orchestrator:latest
    environment:
      - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint: [ /saferwall/orchestrator-svc, -config, /saferwall/conf/ ]
    volumes:
      - samples:/samples
      - /saferwall:/saferwall/storage

  aggregator:
    image: saferwall/aggregator:latest
    depends_on:
      - couchbase
    environment:
      - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint: [ /saferwall/aggregator-svc, -config, /saferwall/conf/ ]
    restart: always

  postprocessor:
    image: saferwall/postprocessor:latest
    environment:
      - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint:
      [
        /saferwall/postprocessor-svc,
        -config,
        /saferwall/conf/
      ]
    volumes:
      - samples:/samples

  pe-svc:
    image: saferwall/pe:latest
    environment:
      - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint: [ /saferwall/pe-svc, -config, /saferwall/conf/ ]
    volumes:
      - samples:/samples

  meta-svc:
    image: saferwall/gometa:latest
    environment:
      - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint: [ /saferwall/meta-svc, -config, /saferwall/conf/ ]
    volumes:
      - samples:/samples

  avira:
    image: saferwall/goavira:latest
    environment:
      - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint: [ /saferwall/avira-svc, -config, /saferwall/conf/ ]
    volumes:
      - samples:/samples

  clamav:
    image: saferwall/goclamav:latest
    environment:
      - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint: [ /saferwall/clamav-svc, -config, /saferwall/conf/ ]
    volumes:
      - samples:/samples

  comodo:
    image: saferwall/gocomodo:latest
    environment:
      - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint: [ /saferwall/comodo-svc, -config, /saferwall/conf/ ]
    volumes:
      - samples:/samples

  msg-publisher:
    image: saferwall/msgpublisher:latest
    environment:
      - SAFERWALL_DEPLOYMENT_KIND=dev
    tty: true
    volumes:
      - samples:/samples

volumes:
  minio_data: null
  couchbase_data: null
  samples: null
