# The address that the gRPC server will listen on.
address = "0.0.0.0:50051"
# Log level verbosity.
log_level = "info"
# Log file where to log.
log_file = "agent.log"
# Hide console window upon startup.
hide_console_window = false
# Text file contaning a list of english words.
english_words = "words.txt"
# The sandbox config file name to write inside the guest.
config_file_name = "config.toml"
# File name of the go template file that we use to generate
# dynamically the sandbox config file.
template_file_name = "filescan.go.tpl"
# The user mode controller component of the sandbox.
controller_name = "exe.exe"
