// Code generated by protoc-gen-go. DO NOT EDIT.
// source: multiav.kaspersky.proto

package kaspersky_api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The scan file request message containing the file path to scan.
type ScanFileRequest struct {
	Filepath             string   `protobuf:"bytes,1,opt,name=filepath,proto3" json:"filepath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanFileRequest) Reset()         { *m = ScanFileRequest{} }
func (m *ScanFileRequest) String() string { return proto.CompactTextString(m) }
func (*ScanFileRequest) ProtoMessage()    {}
func (*ScanFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0679c5a89e6015cf, []int{0}
}

func (m *ScanFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanFileRequest.Unmarshal(m, b)
}
func (m *ScanFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanFileRequest.Marshal(b, m, deterministic)
}
func (m *ScanFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanFileRequest.Merge(m, src)
}
func (m *ScanFileRequest) XXX_Size() int {
	return xxx_messageInfo_ScanFileRequest.Size(m)
}
func (m *ScanFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScanFileRequest proto.InternalMessageInfo

func (m *ScanFileRequest) GetFilepath() string {
	if m != nil {
		return m.Filepath
	}
	return ""
}

// The scan response message containing detection results of the antiVirus.
type ScanResponse struct {
	Output               string   `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Infected             bool     `protobuf:"varint,2,opt,name=infected,proto3" json:"infected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanResponse) Reset()         { *m = ScanResponse{} }
func (m *ScanResponse) String() string { return proto.CompactTextString(m) }
func (*ScanResponse) ProtoMessage()    {}
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0679c5a89e6015cf, []int{1}
}

func (m *ScanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanResponse.Unmarshal(m, b)
}
func (m *ScanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanResponse.Marshal(b, m, deterministic)
}
func (m *ScanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanResponse.Merge(m, src)
}
func (m *ScanResponse) XXX_Size() int {
	return xxx_messageInfo_ScanResponse.Size(m)
}
func (m *ScanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ScanResponse proto.InternalMessageInfo

func (m *ScanResponse) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func (m *ScanResponse) GetInfected() bool {
	if m != nil {
		return m.Infected
	}
	return false
}

func init() {
	proto.RegisterType((*ScanFileRequest)(nil), "kaspersky.api.ScanFileRequest")
	proto.RegisterType((*ScanResponse)(nil), "kaspersky.api.ScanResponse")
}

func init() { proto.RegisterFile("multiav.kaspersky.proto", fileDescriptor_0679c5a89e6015cf) }

var fileDescriptor_0679c5a89e6015cf = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcf, 0x2d, 0xcd, 0x29,
	0xc9, 0x4c, 0x2c, 0xd3, 0xcb, 0x4e, 0x2c, 0x2e, 0x48, 0x2d, 0x2a, 0xce, 0xae, 0xd4, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x45, 0x08, 0x24, 0x16, 0x64, 0x2a, 0xe9, 0x72, 0xf1, 0x07, 0x27,
	0x27, 0xe6, 0xb9, 0x65, 0xe6, 0xa4, 0x06, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x49, 0x71,
	0x71, 0xa4, 0x65, 0xe6, 0xa4, 0x16, 0x24, 0x96, 0x64, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06,
	0xc1, 0xf9, 0x4a, 0x4e, 0x5c, 0x3c, 0x20, 0xe5, 0x41, 0xa9, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9,
	0x42, 0x62, 0x5c, 0x6c, 0xf9, 0xa5, 0x25, 0x05, 0xa5, 0x25, 0x50, 0x95, 0x50, 0x1e, 0xc8, 0x8c,
	0xcc, 0xbc, 0xb4, 0xd4, 0xe4, 0x92, 0xd4, 0x14, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x8e, 0x20, 0x38,
	0xdf, 0x28, 0x96, 0x4b, 0xc0, 0x1b, 0xe6, 0x06, 0x90, 0x61, 0x79, 0xa9, 0x45, 0x42, 0x9e, 0x5c,
	0x1c, 0x30, 0x67, 0x08, 0xc9, 0xe9, 0xa1, 0x38, 0x51, 0x0f, 0xcd, 0x7d, 0x52, 0xd2, 0x58, 0xe4,
	0x61, 0x0e, 0x52, 0x62, 0x48, 0x62, 0x03, 0xfb, 0xd3, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x3f,
	0xf4, 0xa9, 0xc0, 0x02, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KasperskyScannerClient is the client API for KasperskyScanner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KasperskyScannerClient interface {
	// Scan a file
	ScanFile(ctx context.Context, in *ScanFileRequest, opts ...grpc.CallOption) (*ScanResponse, error)
}

type kasperskyScannerClient struct {
	cc *grpc.ClientConn
}

func NewKasperskyScannerClient(cc *grpc.ClientConn) KasperskyScannerClient {
	return &kasperskyScannerClient{cc}
}

func (c *kasperskyScannerClient) ScanFile(ctx context.Context, in *ScanFileRequest, opts ...grpc.CallOption) (*ScanResponse, error) {
	out := new(ScanResponse)
	err := c.cc.Invoke(ctx, "/kaspersky.api.KasperskyScanner/ScanFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KasperskyScannerServer is the server API for KasperskyScanner service.
type KasperskyScannerServer interface {
	// Scan a file
	ScanFile(context.Context, *ScanFileRequest) (*ScanResponse, error)
}

// UnimplementedKasperskyScannerServer can be embedded to have forward compatible implementations.
type UnimplementedKasperskyScannerServer struct {
}

func (*UnimplementedKasperskyScannerServer) ScanFile(ctx context.Context, req *ScanFileRequest) (*ScanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScanFile not implemented")
}

func RegisterKasperskyScannerServer(s *grpc.Server, srv KasperskyScannerServer) {
	s.RegisterService(&_KasperskyScanner_serviceDesc, srv)
}

func _KasperskyScanner_ScanFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KasperskyScannerServer).ScanFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kaspersky.api.KasperskyScanner/ScanFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KasperskyScannerServer).ScanFile(ctx, req.(*ScanFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _KasperskyScanner_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kaspersky.api.KasperskyScanner",
	HandlerType: (*KasperskyScannerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScanFile",
			Handler:    _KasperskyScanner_ScanFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "multiav.kaspersky.proto",
}
