// Copyright 2022 Saferwall. All rights reserved.
// Use of this source code is governed by Apache v2 license
// license that can be found in the LICENSE file.

package meta

// Compilers, Installers, Packers names as seen by DiE (Detect It Easy)
// This map a signature name substring into a tag.
var sigMap = map[string]string{
	"Nullsoft Scriptable Install": "nsis",
	"Inno Setup":                  "innosetup",
	"UPX":                         "upx",
	"FSG":                         "fsg",
	"MEW":                         "mew",
	"PKLITE":                      "pklite",
	"ASPack":                      "aspack",
	"RLPack":                      "rlpack",
	"NsPacK":                      "nspack",
	"ASProtect":                   "asprotect",
	"ACProtect":                   "acprotect",
	"AntiDote":                    "antidote",
	"PECompact":                   "pecompact",
	"PECrypt32":                   "pecrypt32",
	"PE-Armor":                    "pe-armor",
	"PESpin":                      "pespin",
	"PEBundle":                    "pebundle",
	"Petite":                      "petite",
	"PELock":                      "pelock",
	"tElock":                      "telock",
	"PKLITE32":                    "pklite",
	"EXECryptor":                  "execryptor",
	"ExeStealth":                  "exestealth",
	"RCryptor":                    "rcryptor",
	"SDProtector":                 "sdprotector",
	"Obsidium":                    "obsidium",
	"VMProtect":                   "vmprotect",
	"Themida/Winlicense":          "themida-winlicense",
	"MoleBox":                     "molebox",
	"ENIGMA":                      "enigma",
	"MPRESS":                      "mpress",
	"NeoLite":                     "neolite",
	"Armadillo":                   "armadillo",
	"Krypton":                     "krypton",
	"HidePE":                      "hidepe",
	"MSLRH":                       "mslrh",
	"gcc":                         "gcc",
	"MinGW":                       "mingw",
	"Microsoft Visual C/C++":      "vc",
	"Microsoft Visual Basic":      "vb",
	"PureBasic":                   "purebasic",
	"Borland C++":                 "borland-c++",
	"MASM":                        "masm",
	"FASM":                        "fasm",
	"Library: .NET":               "dotnet",
	"MFC":                         "mfc",
	"Yoda's Crypter":              "yodascrypter",
	"Delphi":                      "delphi",
	"AutoIt":                      "autoit",
	"StarForce":                   "starforce",
	"eXPressor":                   "expressor",
	"sfx: Microsoft Cabinet":      "sfx-cab",
	"sfx: 7-Zip":                  "sfx-7z",
	"sfx: WinZip":                 "sfx-zip",
	"sfx: WinACE":                 "sfx-ace",
	"Smart Assembly":              "smart-assembly",
	".NET Reactor":                "dotnet-reactor",
	"Babel .NET":                  "babel.net",
	"Confuser":                    "confuser",
	"Dotfuscator":                 "dotfuscator",
	"Eazfuscator":                 "eazfuscator",
	"InstallShield":               "installshield",
	"Inno Setup Module":           "innosetup",
	"Enigma Installer":            "enigma-install",
	"FDM Installer":               "fdm-install",
	"Gentee Installer":            "gentee-install",
	"Ghost Installer":             "ghost-install",
}

var typeMap = map[string]string{
	"MS-DOS":                  "msdos",
	"PE32":                    "pe",
	"ELF":                     "elf",
	"Mach-O":                  "mach-o",
	"MS Windows shortcut":     "lnk",
	"XML":                     "xml",
	"HTML":                    "html",
	"PDF":                     "pdf",
	"Macromedia Flash":        "swf",
	"DOS batch file":          "bat",
	"Zip archive data":        "zip",
	"RAR archive data":        "rar",
	"7-zip archive data":      "7-zip",
	"gzip compressed data":    "gzip",
	"Java archive data (JAR)": "jar",
	"JPEG image data":         "jpeg",
	"PNG image data":          "png",
	"GIF image data":          "gif",
	"SVG Scalable Vector":     "svg",
	"Rich Text Format":        "rtf",
}
