// Code generated by protoc-gen-go. DO NOT EDIT.
// source: multiav.drweb.proto

package drweb_api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The scan file request message containing the file path to scan.
type ScanFileRequest struct {
	Filepath             string   `protobuf:"bytes,1,opt,name=filepath,proto3" json:"filepath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanFileRequest) Reset()         { *m = ScanFileRequest{} }
func (m *ScanFileRequest) String() string { return proto.CompactTextString(m) }
func (*ScanFileRequest) ProtoMessage()    {}
func (*ScanFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f164663ba98af3d, []int{0}
}

func (m *ScanFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanFileRequest.Unmarshal(m, b)
}
func (m *ScanFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanFileRequest.Marshal(b, m, deterministic)
}
func (m *ScanFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanFileRequest.Merge(m, src)
}
func (m *ScanFileRequest) XXX_Size() int {
	return xxx_messageInfo_ScanFileRequest.Size(m)
}
func (m *ScanFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScanFileRequest proto.InternalMessageInfo

func (m *ScanFileRequest) GetFilepath() string {
	if m != nil {
		return m.Filepath
	}
	return ""
}

// The scan response message containing detection results of the antiVirus.
type ScanResponse struct {
	Output               string   `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Infected             bool     `protobuf:"varint,2,opt,name=infected,proto3" json:"infected,omitempty"`
	Update               int64    `protobuf:"varint,3,opt,name=update,proto3" json:"update,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanResponse) Reset()         { *m = ScanResponse{} }
func (m *ScanResponse) String() string { return proto.CompactTextString(m) }
func (*ScanResponse) ProtoMessage()    {}
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f164663ba98af3d, []int{1}
}

func (m *ScanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanResponse.Unmarshal(m, b)
}
func (m *ScanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanResponse.Marshal(b, m, deterministic)
}
func (m *ScanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanResponse.Merge(m, src)
}
func (m *ScanResponse) XXX_Size() int {
	return xxx_messageInfo_ScanResponse.Size(m)
}
func (m *ScanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ScanResponse proto.InternalMessageInfo

func (m *ScanResponse) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func (m *ScanResponse) GetInfected() bool {
	if m != nil {
		return m.Infected
	}
	return false
}

func (m *ScanResponse) GetUpdate() int64 {
	if m != nil {
		return m.Update
	}
	return 0
}

// The version request message ask for version.
type VersionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionRequest) Reset()         { *m = VersionRequest{} }
func (m *VersionRequest) String() string { return proto.CompactTextString(m) }
func (*VersionRequest) ProtoMessage()    {}
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f164663ba98af3d, []int{2}
}

func (m *VersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionRequest.Unmarshal(m, b)
}
func (m *VersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionRequest.Marshal(b, m, deterministic)
}
func (m *VersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionRequest.Merge(m, src)
}
func (m *VersionRequest) XXX_Size() int {
	return xxx_messageInfo_VersionRequest.Size(m)
}
func (m *VersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VersionRequest proto.InternalMessageInfo

// The response message containing program/VPS version.
type VersionResponse struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f164663ba98af3d, []int{3}
}

func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*ScanFileRequest)(nil), "drweb.api.ScanFileRequest")
	proto.RegisterType((*ScanResponse)(nil), "drweb.api.ScanResponse")
	proto.RegisterType((*VersionRequest)(nil), "drweb.api.VersionRequest")
	proto.RegisterType((*VersionResponse)(nil), "drweb.api.VersionResponse")
}

func init() { proto.RegisterFile("multiav.drweb.proto", fileDescriptor_2f164663ba98af3d) }

var fileDescriptor_2f164663ba98af3d = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0x8d, 0x0b, 0x6b, 0x77, 0x58, 0x5c, 0x89, 0xa0, 0x35, 0xa7, 0x92, 0x53, 0x41, 0xec,
	0x41, 0x3f, 0x81, 0xe0, 0x9f, 0x7b, 0x04, 0x05, 0x6f, 0xe9, 0x76, 0x16, 0x03, 0x35, 0x89, 0xe9,
	0x64, 0xfd, 0x2a, 0x7e, 0x5c, 0xa9, 0x9b, 0x06, 0x5d, 0x3c, 0xfe, 0x66, 0x5e, 0xe6, 0xbd, 0x17,
	0x38, 0x7d, 0x8f, 0x3d, 0x19, 0xbd, 0x6d, 0xba, 0xf0, 0x89, 0x6d, 0xe3, 0x83, 0x23, 0xc7, 0x17,
	0x3b, 0xd0, 0xde, 0xc8, 0x2b, 0x58, 0x3d, 0xad, 0xb5, 0x7d, 0x30, 0x3d, 0x2a, 0xfc, 0x88, 0x38,
	0x10, 0x17, 0x50, 0x6c, 0x4c, 0x8f, 0x5e, 0xd3, 0x5b, 0xc9, 0x2a, 0x56, 0x2f, 0x54, 0x66, 0xf9,
	0x0a, 0xcb, 0x51, 0xae, 0x70, 0xf0, 0xce, 0x0e, 0xc8, 0xcf, 0x60, 0xee, 0x22, 0xf9, 0x48, 0x49,
	0x99, 0x68, 0xbc, 0x61, 0xec, 0x06, 0xd7, 0x84, 0x5d, 0x79, 0x58, 0xb1, 0xba, 0x50, 0x99, 0xc7,
	0x37, 0xd1, 0x77, 0x9a, 0xb0, 0x9c, 0x55, 0xac, 0x9e, 0xa9, 0x44, 0xf2, 0x04, 0x8e, 0x9f, 0x31,
	0x0c, 0xc6, 0xd9, 0x94, 0x44, 0x5e, 0xc2, 0x2a, 0x4f, 0x92, 0x61, 0x09, 0x47, 0xdb, 0xdd, 0x28,
	0x39, 0x4e, 0x78, 0xfd, 0xc5, 0x60, 0x79, 0x17, 0x5e, 0xb0, 0x1d, 0x03, 0x5a, 0x0c, 0xfc, 0x16,
	0x8a, 0xa9, 0x1a, 0x17, 0x4d, 0xae, 0xdc, 0xec, 0xf5, 0x15, 0xe7, 0x7b, 0xbb, 0xc9, 0x4b, 0x1e,
	0xf0, 0x7b, 0x80, 0x47, 0xa4, 0x94, 0x81, 0x5f, 0xfc, 0x12, 0xfe, 0x4d, 0x2a, 0xc4, 0x7f, 0xab,
	0xe9, 0x4c, 0x3b, 0xff, 0xf9, 0xf6, 0x9b, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7c, 0xff, 0x7b,
	0xd9, 0x8d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DrWebScannerClient is the client API for DrWebScanner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DrWebScannerClient interface {
	// Scan a file
	ScanFile(ctx context.Context, in *ScanFileRequest, opts ...grpc.CallOption) (*ScanResponse, error)
	// Get program version
	GetVersion(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
}

type drWebScannerClient struct {
	cc *grpc.ClientConn
}

func NewDrWebScannerClient(cc *grpc.ClientConn) DrWebScannerClient {
	return &drWebScannerClient{cc}
}

func (c *drWebScannerClient) ScanFile(ctx context.Context, in *ScanFileRequest, opts ...grpc.CallOption) (*ScanResponse, error) {
	out := new(ScanResponse)
	err := c.cc.Invoke(ctx, "/drweb.api.DrWebScanner/ScanFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drWebScannerClient) GetVersion(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/drweb.api.DrWebScanner/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DrWebScannerServer is the server API for DrWebScanner service.
type DrWebScannerServer interface {
	// Scan a file
	ScanFile(context.Context, *ScanFileRequest) (*ScanResponse, error)
	// Get program version
	GetVersion(context.Context, *VersionRequest) (*VersionResponse, error)
}

// UnimplementedDrWebScannerServer can be embedded to have forward compatible implementations.
type UnimplementedDrWebScannerServer struct {
}

func (*UnimplementedDrWebScannerServer) ScanFile(ctx context.Context, req *ScanFileRequest) (*ScanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScanFile not implemented")
}
func (*UnimplementedDrWebScannerServer) GetVersion(ctx context.Context, req *VersionRequest) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersion not implemented")
}

func RegisterDrWebScannerServer(s *grpc.Server, srv DrWebScannerServer) {
	s.RegisterService(&_DrWebScanner_serviceDesc, srv)
}

func _DrWebScanner_ScanFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrWebScannerServer).ScanFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drweb.api.DrWebScanner/ScanFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrWebScannerServer).ScanFile(ctx, req.(*ScanFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DrWebScanner_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrWebScannerServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drweb.api.DrWebScanner/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrWebScannerServer).GetVersion(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DrWebScanner_serviceDesc = grpc.ServiceDesc{
	ServiceName: "drweb.api.DrWebScanner",
	HandlerType: (*DrWebScannerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScanFile",
			Handler:    _DrWebScanner_ScanFile_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _DrWebScanner_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "multiav.drweb.proto",
}
