# Log level verbosity.
log_level = "debug"
# Shared volume between all microservices.
shared_volume = "/samples"

[producer]
# The data source name (DSN) for connecting to the broker server (NSQD).
nsqd = "nsqd:4150"

[consumer]
# The data source name (DSN) for connecting to the service discovery server
# (NSQLookupD).
lookupds = ["nsqlookupd:4161"]
# Topic name to consume from.
topic = "topic-filescan"
# Channel name used in conjunction with topic name.
channel = "chan-filescan"
# The number of concurrent workers to process the jobs.
concurrency = 1

[storage]
# Deployement kind, possible values: aws, minio, local.
deployment_kind = "minio"
# Bucket name where samples are stored.
bucket = "saferwall-samples"
    # Only one storage type has to be provided. `deployment_kind` controls
    # at runtime which one to use.
    [storage.s3]
    region = "us-east-1" # AWS region.
    secret_key = "superSecretKey" # AWS Secret Access Key.
    access_key = "superSecretAccessKey" # AWS Access key ID.
    [storage.minio]
    endpoint = "minio:9000" # MinIO endpoint.
    region = "us-east-1" # Region.
    access_key = "minio" # Access key ID.
    secret_key = "minio123" # Secret Access Key.
    [storage.local]
    root_dir = "/saferwall/storage" # Full path to the directory where to store the files.
