# Log level verbosity.
log_level = "debug"
# Shared volume between all microservices.
shared_volume = "/samples"
# Name of the antivirus.
engine_name = "sophos"
# Scan timeout duration.
scan_timeout = "60s"

[producer]
# The data source name (DSN) for connecting to the broker server (NSQD).
nsqd = "localhost:4150"
# Topic name to produce to.
topic = "topic-aggregator"

[consumer]
# The data source name (DSN) for connecting to the service discovery server
# (NSQLookupD).
lookupds = ["localhost:4161"]
# Topic name to consume from.
topic = "topic-multiav"
# Channel name used in conjunction with topic name.
channel = "chan-sophos"
# The number of concurrent workers to process the jobs.
concurrency = 1
