// Code generated by protoc-gen-go. DO NOT EDIT.
// source: multiav.dummy.proto

package dummy_api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The scan file request message containing the file path to scan.
type ScanFileRequest struct {
	Filepath             string   `protobuf:"bytes,1,opt,name=filepath,proto3" json:"filepath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanFileRequest) Reset()         { *m = ScanFileRequest{} }
func (m *ScanFileRequest) String() string { return proto.CompactTextString(m) }
func (*ScanFileRequest) ProtoMessage()    {}
func (*ScanFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_131257496a34347d, []int{0}
}

func (m *ScanFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanFileRequest.Unmarshal(m, b)
}
func (m *ScanFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanFileRequest.Marshal(b, m, deterministic)
}
func (m *ScanFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanFileRequest.Merge(m, src)
}
func (m *ScanFileRequest) XXX_Size() int {
	return xxx_messageInfo_ScanFileRequest.Size(m)
}
func (m *ScanFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScanFileRequest proto.InternalMessageInfo

func (m *ScanFileRequest) GetFilepath() string {
	if m != nil {
		return m.Filepath
	}
	return ""
}

// The scan response message containing detection results of the antiVirus.
type ScanResponse struct {
	Output               string   `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Infected             bool     `protobuf:"varint,2,opt,name=infected,proto3" json:"infected,omitempty"`
	Update               int64    `protobuf:"varint,3,opt,name=update,proto3" json:"update,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanResponse) Reset()         { *m = ScanResponse{} }
func (m *ScanResponse) String() string { return proto.CompactTextString(m) }
func (*ScanResponse) ProtoMessage()    {}
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_131257496a34347d, []int{1}
}

func (m *ScanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanResponse.Unmarshal(m, b)
}
func (m *ScanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanResponse.Marshal(b, m, deterministic)
}
func (m *ScanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanResponse.Merge(m, src)
}
func (m *ScanResponse) XXX_Size() int {
	return xxx_messageInfo_ScanResponse.Size(m)
}
func (m *ScanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ScanResponse proto.InternalMessageInfo

func (m *ScanResponse) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func (m *ScanResponse) GetInfected() bool {
	if m != nil {
		return m.Infected
	}
	return false
}

func (m *ScanResponse) GetUpdate() int64 {
	if m != nil {
		return m.Update
	}
	return 0
}

func init() {
	proto.RegisterType((*ScanFileRequest)(nil), "dummy.api.ScanFileRequest")
	proto.RegisterType((*ScanResponse)(nil), "dummy.api.ScanResponse")
}

func init() { proto.RegisterFile("multiav.dummy.proto", fileDescriptor_131257496a34347d) }

var fileDescriptor_131257496a34347d = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0x41, 0xcb, 0x82, 0x40,
	0x10, 0x86, 0xbf, 0xfd, 0x04, 0xd1, 0x45, 0x08, 0x36, 0x28, 0xf1, 0x24, 0x9e, 0xbc, 0xb4, 0x87,
	0xfa, 0x05, 0x41, 0x74, 0x6f, 0xbb, 0x75, 0xdb, 0x74, 0xa4, 0x05, 0xdd, 0xdd, 0x74, 0x36, 0xe8,
	0xdf, 0xc7, 0x96, 0x7a, 0xf0, 0xf8, 0x30, 0xef, 0xcc, 0x3c, 0x2f, 0x5d, 0x77, 0xae, 0x45, 0x25,
	0x5f, 0xbc, 0x76, 0x5d, 0xf7, 0xe6, 0xb6, 0x37, 0x68, 0x58, 0xfc, 0x03, 0x69, 0x55, 0xb1, 0xa3,
	0xab, 0x6b, 0x25, 0xf5, 0x59, 0xb5, 0x20, 0xe0, 0xe9, 0x60, 0x40, 0x96, 0xd1, 0xa8, 0x51, 0x2d,
	0x58, 0x89, 0x8f, 0x94, 0xe4, 0xa4, 0x8c, 0xc5, 0xcc, 0xc5, 0x8d, 0x26, 0x3e, 0x2e, 0x60, 0xb0,
	0x46, 0x0f, 0xc0, 0x36, 0x34, 0x34, 0x0e, 0xad, 0xc3, 0x31, 0x39, 0x92, 0xbf, 0xa1, 0x74, 0x03,
	0x15, 0x42, 0x9d, 0xfe, 0xe7, 0xa4, 0x8c, 0xc4, 0xcc, 0x7e, 0xc7, 0xd9, 0x5a, 0x22, 0xa4, 0x41,
	0x4e, 0xca, 0x40, 0x8c, 0xb4, 0xbf, 0xd0, 0xe4, 0xe4, 0xbd, 0xfc, 0x03, 0x0d, 0x3d, 0x3b, 0xd2,
	0x68, 0x52, 0x63, 0x19, 0x9f, 0x95, 0xf9, 0xc2, 0x37, 0xdb, 0x2e, 0x66, 0x93, 0x5c, 0xf1, 0x77,
	0x0f, 0xbf, 0x7d, 0x0f, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe8, 0xa1, 0x87, 0xf3, 0x06, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DummyScannerClient is the client API for DummyScanner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DummyScannerClient interface {
	// Scan a file
	ScanFile(ctx context.Context, in *ScanFileRequest, opts ...grpc.CallOption) (*ScanResponse, error)
}

type dummyScannerClient struct {
	cc *grpc.ClientConn
}

func NewDummyScannerClient(cc *grpc.ClientConn) DummyScannerClient {
	return &dummyScannerClient{cc}
}

func (c *dummyScannerClient) ScanFile(ctx context.Context, in *ScanFileRequest, opts ...grpc.CallOption) (*ScanResponse, error) {
	out := new(ScanResponse)
	err := c.cc.Invoke(ctx, "/dummy.api.DummyScanner/ScanFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DummyScannerServer is the server API for DummyScanner service.
type DummyScannerServer interface {
	// Scan a file
	ScanFile(context.Context, *ScanFileRequest) (*ScanResponse, error)
}

// UnimplementedDummyScannerServer can be embedded to have forward compatible implementations.
type UnimplementedDummyScannerServer struct {
}

func (*UnimplementedDummyScannerServer) ScanFile(ctx context.Context, req *ScanFileRequest) (*ScanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScanFile not implemented")
}

func RegisterDummyScannerServer(s *grpc.Server, srv DummyScannerServer) {
	s.RegisterService(&_DummyScanner_serviceDesc, srv)
}

func _DummyScanner_ScanFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DummyScannerServer).ScanFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dummy.api.DummyScanner/ScanFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DummyScannerServer).ScanFile(ctx, req.(*ScanFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DummyScanner_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dummy.api.DummyScanner",
	HandlerType: (*DummyScannerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScanFile",
			Handler:    _DummyScanner_ScanFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "multiav.dummy.proto",
}
