name: Update Antivirus signatures
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
env:
  org: saferwall
jobs:
  release:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        service:
          - goavira
          - goavast
          - gobitdefender
          - goclamav
          - gocomodo
          - godrweb
          - goeset
          - gofsecure
          - gokaspersky
          - gomcafee
          - gosophos
          - gosymantec
          - gotrendmicro
          - gowindefender
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate build version
        id: prep
        run: |
          version=$(cat VERSION)
          echo "::set-output name=BUILD_VERSION::${version}"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: build/docker/Dockerfile.${{ matrix.service }}
          build-args: |
            GITHUB_USER=${{ secrets.GIT_USERNAME }}
            GITHUB_TOKEN=${{ secrets.GIT_TOKEN }}
          tags: |
            ${{ env.org }}/${{ matrix.service }}:latest
            ${{ env.org }}/${{ matrix.service }}:${{ steps.prep.outputs.BUILD_VERSION }}
