name: Release
on: pull_request
env:
  org: saferwall
jobs:
  release:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        service: [pe, meta, gometa, aggregator, orchestrator, goavira, goclamav, gocomodo, gowindefender]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate build version
        id: prep
        run: |
          version=$(cat VERSION)
          echo "::set-output name=BUILD_VERSION::${version}"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: build/docker/Dockerfile.${{ matrix.service }}
          build-args: |
            GITHUB_USER=${{ secrets.GIT_USERNAME }}
            GITHUB_TOKEN=${{ secrets.GIT_TOKEN }}
          tags: |
            ${{ env.org }}/${{ matrix.service }}:latest
            ${{ env.org }}/${{ matrix.service }}:${{ steps.prep.outputs.BUILD_VERSION }}