name: build and test
on: [push]
jobs:
  test:
    name: Build & Test
    strategy:
      matrix:
        go-version: [1.21.x]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: |
          go version
          go env -w GOPRIVATE=github.com/saferwall/*
          git config --global url."https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_TOKEN }}@github.com".insteadOf "https://github.com"
          go get -u golang.org/x/lint/golint
          make exiftool-install
          make die-install
          make trid-install
          make yara-install
          sudo apt install -qq wamerican liblua5.4-dev

      - name: Build
        run: |
          go env -w GOFLAGS=-mod=mod
          go build -v -tags lua54 ./...

      - name: Test With Coverage
        run: |
          export LC_ALL=C
          go test -tags lua54 $(go list ./... | grep -v /multiav/) -race -coverprofile=coverage.out -covermode=atomic

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2

      - name: Go vet
        run: |
          go vet -tags lua54 -v ./...

      - name: Staticcheck
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2023.1"
          install-go: false
          cache-key: ${{ matrix.go-version }}
          build-tags: lua54
