name: Generate Vagrant Box
on:
  workflow_dispatch:

jobs:
  build-vagrant-box:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install VirtualBox|Vagrant
        run: |
          make vbox-install
          make vagrant-install

      - name: Create Vagrant box
        run: |
          cd build/vagrant
          vagrant up

      - name: Create box package
        run: make vagrant-package

      - name: Authenticate to Vagrant cloud
        run: make vagrant-login
        env:
          VAGRANT_TOKEN: ${{ secrets.VAGRANT_TOKEN }}

      - name: Publish the box
        run: make vagrant-publish
