# Log level verbosity.
log_level = "debug"
# Shared volume between all microservices.
shared_volume = "/samples"
# Text file contaning a list of english words.
english_words = "words.txt"
# Path to the yara rules directory. The content of the directory
# should include an index.yara that include all other yara rules.
yara_rules = "./rules"

[agent]
# Destinary directory inside the guest where the agent is deployed.
dest_dir = "C:\\saferwall\\"
# The sandbox binary components.
package_name = "/saferwall/package.zip"

[virt_manager]
# Specify whether a remote or local session.
# Local session uses "unix" and ignore the fields below.
network = "ssh"
# IP address of the host running libvirt RPC server.
address = "192.168.1.11"
# Port number of the SSH server.
port = "22"
# The username used when connecting via a remote transport connection.
user = "ayb"
# File path of the SSH private key when using remote transport.
ssh_key_path = "id_rsa"
# Snapshot name to restore to to go back to a clean state.
snapshot_name = "clean-state"

[producer]
# The data source name (DSN) for connecting to the broker server (NSQD).
nsqd = "nsqd:4150"
# Topic name to produce to.
topic = "topic-aggregator"

[consumer]
# The data source name (DSN) for connecting to the service discovery server
# (NSQLookupD).
lookupds = ["nsqlookupd:4161"]
# Topic name to consume from.
topic = "topic-sandbox"
# Channel name used in conjunction with topic name.
channel = "chan-sandbox"
# The number of concurrent workers to process the jobs.
concurrency = 1
