// Code generated by protoc-gen-go. DO NOT EDIT.
// source: multiav.avira.proto

package avira_api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The scan file request message containing the file path to scan.
type ScanFileRequest struct {
	Filepath             string   `protobuf:"bytes,1,opt,name=filepath,proto3" json:"filepath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanFileRequest) Reset()         { *m = ScanFileRequest{} }
func (m *ScanFileRequest) String() string { return proto.CompactTextString(m) }
func (*ScanFileRequest) ProtoMessage()    {}
func (*ScanFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_604db18eda163269, []int{0}
}

func (m *ScanFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanFileRequest.Unmarshal(m, b)
}
func (m *ScanFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanFileRequest.Marshal(b, m, deterministic)
}
func (m *ScanFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanFileRequest.Merge(m, src)
}
func (m *ScanFileRequest) XXX_Size() int {
	return xxx_messageInfo_ScanFileRequest.Size(m)
}
func (m *ScanFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScanFileRequest proto.InternalMessageInfo

func (m *ScanFileRequest) GetFilepath() string {
	if m != nil {
		return m.Filepath
	}
	return ""
}

// The scan response message containing detection results of the antiVirus.
type ScanResponse struct {
	Output               string   `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Infected             bool     `protobuf:"varint,2,opt,name=infected,proto3" json:"infected,omitempty"`
	Update               int64    `protobuf:"varint,3,opt,name=update,proto3" json:"update,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanResponse) Reset()         { *m = ScanResponse{} }
func (m *ScanResponse) String() string { return proto.CompactTextString(m) }
func (*ScanResponse) ProtoMessage()    {}
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_604db18eda163269, []int{1}
}

func (m *ScanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanResponse.Unmarshal(m, b)
}
func (m *ScanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanResponse.Marshal(b, m, deterministic)
}
func (m *ScanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanResponse.Merge(m, src)
}
func (m *ScanResponse) XXX_Size() int {
	return xxx_messageInfo_ScanResponse.Size(m)
}
func (m *ScanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ScanResponse proto.InternalMessageInfo

func (m *ScanResponse) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func (m *ScanResponse) GetInfected() bool {
	if m != nil {
		return m.Infected
	}
	return false
}

func (m *ScanResponse) GetUpdate() int64 {
	if m != nil {
		return m.Update
	}
	return 0
}

// The license request message contains the license in binary format.
type LicenseRequest struct {
	License              []byte   `protobuf:"bytes,1,opt,name=license,proto3" json:"license,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LicenseRequest) Reset()         { *m = LicenseRequest{} }
func (m *LicenseRequest) String() string { return proto.CompactTextString(m) }
func (*LicenseRequest) ProtoMessage()    {}
func (*LicenseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_604db18eda163269, []int{2}
}

func (m *LicenseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LicenseRequest.Unmarshal(m, b)
}
func (m *LicenseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LicenseRequest.Marshal(b, m, deterministic)
}
func (m *LicenseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LicenseRequest.Merge(m, src)
}
func (m *LicenseRequest) XXX_Size() int {
	return xxx_messageInfo_LicenseRequest.Size(m)
}
func (m *LicenseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LicenseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LicenseRequest proto.InternalMessageInfo

func (m *LicenseRequest) GetLicense() []byte {
	if m != nil {
		return m.License
	}
	return nil
}

// The license response message.
type LicenseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LicenseResponse) Reset()         { *m = LicenseResponse{} }
func (m *LicenseResponse) String() string { return proto.CompactTextString(m) }
func (*LicenseResponse) ProtoMessage()    {}
func (*LicenseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_604db18eda163269, []int{3}
}

func (m *LicenseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LicenseResponse.Unmarshal(m, b)
}
func (m *LicenseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LicenseResponse.Marshal(b, m, deterministic)
}
func (m *LicenseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LicenseResponse.Merge(m, src)
}
func (m *LicenseResponse) XXX_Size() int {
	return xxx_messageInfo_LicenseResponse.Size(m)
}
func (m *LicenseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LicenseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LicenseResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ScanFileRequest)(nil), "avira.api.ScanFileRequest")
	proto.RegisterType((*ScanResponse)(nil), "avira.api.ScanResponse")
	proto.RegisterType((*LicenseRequest)(nil), "avira.api.LicenseRequest")
	proto.RegisterType((*LicenseResponse)(nil), "avira.api.LicenseResponse")
}

func init() { proto.RegisterFile("multiav.avira.proto", fileDescriptor_604db18eda163269) }

var fileDescriptor_604db18eda163269 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4e, 0x84, 0x30,
	0x18, 0x84, 0xad, 0x9b, 0xac, 0xec, 0x1f, 0x22, 0xb1, 0x26, 0x8a, 0x3d, 0x91, 0x9e, 0x88, 0x89,
	0x1c, 0xf4, 0x09, 0xb8, 0x78, 0x30, 0x9e, 0xea, 0xcd, 0x5b, 0x65, 0xff, 0x8d, 0x4d, 0xb0, 0x54,
	0xf8, 0xcb, 0xdb, 0xf8, 0xae, 0xa6, 0x0b, 0x34, 0x4a, 0xf6, 0xf8, 0x75, 0xa6, 0xd3, 0x99, 0xc2,
	0xf5, 0x97, 0x6f, 0xc9, 0xe8, 0xb1, 0xd2, 0xa3, 0xe9, 0x75, 0xe5, 0xfa, 0x8e, 0x3a, 0xbe, 0x9b,
	0x40, 0x3b, 0x23, 0x1f, 0x20, 0x7b, 0x6b, 0xb4, 0x7d, 0x36, 0x2d, 0x2a, 0xfc, 0xf6, 0x38, 0x10,
	0x17, 0x90, 0x1c, 0x4c, 0x8b, 0x4e, 0xd3, 0x67, 0xce, 0x0a, 0x56, 0xee, 0x54, 0x64, 0xf9, 0x0e,
	0x69, 0xb0, 0x2b, 0x1c, 0x5c, 0x67, 0x07, 0xe4, 0x37, 0xb0, 0xed, 0x3c, 0x39, 0x4f, 0xb3, 0x73,
	0xa6, 0x90, 0x61, 0xec, 0x01, 0x1b, 0xc2, 0x7d, 0x7e, 0x5e, 0xb0, 0x32, 0x51, 0x91, 0xc3, 0x1d,
	0xef, 0xf6, 0x9a, 0x30, 0xdf, 0x14, 0xac, 0xdc, 0xa8, 0x99, 0xe4, 0x3d, 0x5c, 0xbe, 0x9a, 0x06,
	0xed, 0x10, 0x9b, 0xe4, 0x70, 0xd1, 0x4e, 0x27, 0xc7, 0xf8, 0x54, 0x2d, 0x28, 0xaf, 0x20, 0x8b,
	0xde, 0xa9, 0xca, 0xe3, 0x0f, 0x83, 0xb4, 0x0e, 0xbb, 0x42, 0x41, 0x8b, 0x3d, 0xaf, 0x21, 0x59,
	0xa6, 0x71, 0x51, 0xc5, 0xc9, 0xd5, 0x6a, 0xaf, 0xb8, 0x5d, 0x69, 0x4b, 0xa2, 0x3c, 0xe3, 0x2f,
	0x90, 0xd5, 0x0d, 0x99, 0x51, 0x13, 0xce, 0xcf, 0xf1, 0xbb, 0x3f, 0xee, 0xff, 0x75, 0x85, 0x38,
	0x25, 0x2d, 0x59, 0x1f, 0xdb, 0xe3, 0xdf, 0x3f, 0xfd, 0x06, 0x00, 0x00, 0xff, 0xff, 0xf7, 0xdb,
	0x45, 0xff, 0x92, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AviraScannerClient is the client API for AviraScanner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AviraScannerClient interface {
	// Scan a file
	ScanFile(ctx context.Context, in *ScanFileRequest, opts ...grpc.CallOption) (*ScanResponse, error)
	// Activate product license
	ActivateLicense(ctx context.Context, in *LicenseRequest, opts ...grpc.CallOption) (*LicenseResponse, error)
}

type aviraScannerClient struct {
	cc *grpc.ClientConn
}

func NewAviraScannerClient(cc *grpc.ClientConn) AviraScannerClient {
	return &aviraScannerClient{cc}
}

func (c *aviraScannerClient) ScanFile(ctx context.Context, in *ScanFileRequest, opts ...grpc.CallOption) (*ScanResponse, error) {
	out := new(ScanResponse)
	err := c.cc.Invoke(ctx, "/avira.api.AviraScanner/ScanFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aviraScannerClient) ActivateLicense(ctx context.Context, in *LicenseRequest, opts ...grpc.CallOption) (*LicenseResponse, error) {
	out := new(LicenseResponse)
	err := c.cc.Invoke(ctx, "/avira.api.AviraScanner/ActivateLicense", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AviraScannerServer is the server API for AviraScanner service.
type AviraScannerServer interface {
	// Scan a file
	ScanFile(context.Context, *ScanFileRequest) (*ScanResponse, error)
	// Activate product license
	ActivateLicense(context.Context, *LicenseRequest) (*LicenseResponse, error)
}

// UnimplementedAviraScannerServer can be embedded to have forward compatible implementations.
type UnimplementedAviraScannerServer struct {
}

func (*UnimplementedAviraScannerServer) ScanFile(ctx context.Context, req *ScanFileRequest) (*ScanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScanFile not implemented")
}
func (*UnimplementedAviraScannerServer) ActivateLicense(ctx context.Context, req *LicenseRequest) (*LicenseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateLicense not implemented")
}

func RegisterAviraScannerServer(s *grpc.Server, srv AviraScannerServer) {
	s.RegisterService(&_AviraScanner_serviceDesc, srv)
}

func _AviraScanner_ScanFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AviraScannerServer).ScanFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/avira.api.AviraScanner/ScanFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AviraScannerServer).ScanFile(ctx, req.(*ScanFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AviraScanner_ActivateLicense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LicenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AviraScannerServer).ActivateLicense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/avira.api.AviraScanner/ActivateLicense",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AviraScannerServer).ActivateLicense(ctx, req.(*LicenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AviraScanner_serviceDesc = grpc.ServiceDesc{
	ServiceName: "avira.api.AviraScanner",
	HandlerType: (*AviraScannerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScanFile",
			Handler:    _AviraScanner_ScanFile_Handler,
		},
		{
			MethodName: "ActivateLicense",
			Handler:    _AviraScanner_ActivateLicense_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "multiav.avira.proto",
}
